### ISSUE TITLE
 Cannot call this method in a scroll callback.

### ISSUE THREAD

**Issue by captain-miao** [captain-miao/RecyclerViewUtils#27]
Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
                                                                                    java.lang.IllegalStateException: 
                                                                                        at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2581)
                                                                                        at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4951)
                                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11383)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:6745)
                                                                                        at com.github.captain_miao.recyclerviewutils.BaseWrapperRecyclerAdapter.showLoadMoreView(BaseWrapperRecyclerAdapter.java:433)
                                                                                        at com.github.captain_miao.recyclerviewutils.WrapperRecyclerView.showLoadMoreView(WrapperRecyclerView.java:259)
                                                                                        at com.github.captain_miao.agera.tutorial.recycleview.ComplexRecycleViewActivity.onLoadMore(ComplexRecycleViewActivity.java:65)
                                                                                        at com.github.captain_miao.recyclerviewutils.WrapperRecyclerView$2.onLoadMore(WrapperRecyclerView.java:129)
                                                                                        at com.github.captain_miao.recyclerviewutils.listener.LinearLayoutWithRecyclerOnScrollListener.onScrolled(LinearLayoutWithRecyclerOnScrollListener.java:66)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
                                                                                        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4776)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:605)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5442)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by captain-miao** [comment]
It's work, use post.
```
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                mAdapter.notifyDataSetChanged();
            }
        });
```

**Comment by soonsam123** [comment]
Thanks! It just works fine 👍
